/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'crema': '#fff7e1',
        'azul': '#034ba5',
        'azul-dark': '#023a80',
        'azul-light': '#e8f0fe',
        'brand-navy': '#0f2e3d',
        'primary': '#034ba5',
        'primary-container': '#023a80',
        'primary-fixed': '#d1e3ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001c3a',
        'secondary': '#034ba5',
        'secondary-container': '#d1e3ff',
        'on-secondary': '#ffffff',
        'tertiary': '#059669',
        'tertiary-container': '#047857',
        'tertiary-fixed': '#a7f3d0',
        'tertiary-fixed-dim': '#6ee7b7',
        'on-tertiary-fixed': '#002114',
        'surface': '#fff7e1',
        'surface-container': '#f5eedd',
        'surface-container-low': '#faf5e8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ece5d4',
        'surface-container-highest': '#e0d9c8',
        'surface-dim': '#ddd6c5',
        'surface-variant': '#e0d9c8',
        'surface-bright': '#fff7e1',
        'surface-tint': '#034ba5',
        'background': '#fff7e1',
        'on-surface': '#1c1b16',
        'on-surface-variant': '#49473f',
        'outline': '#7a7768',
        'outline-variant': '#cbc4b4',
        'inverse-surface': '#31302b',
        'inverse-on-surface': '#f4efe4',
        'inverse-primary': '#a8c8ff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'margin-tablet': '2.5rem',
        'margin-mobile': '1.25rem',
        'margin-desktop': '4rem',
        'space-sm': '0.75rem',
        'gutter-tablet': '1.5rem',
        'space-2xl': '3rem',
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-xl': '2rem',
        'gutter-desktop': '1.5rem',
        'space-3xl': '4.5rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        'heading': ['Manrope', 'Montserrat', 'sans-serif'],
        'body': ['Manrope', 'Montserrat', 'sans-serif'],
        'display': ['Manrope', 'Montserrat', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'title-lg': ['Manrope', 'sans-serif'],
        'title-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'label-lg': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-sm': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-lg': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
