import { Link } from 'react-router-dom';
import { projects } from '../data/projects';

const Projects = () => (
  <div className="flex w-full flex-col bg-crema pt-20">
    <section className="relative w-full overflow-hidden bg-crema pt-space-2xl shadow-sm lg:pt-space-3xl">
      <div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(#034ba5_1px,transparent_1px)] [background-size:24px_24px]" />
      <div className="relative mx-auto max-w-[1280px] px-gutter-mobile pb-space-3xl lg:px-gutter-desktop">
        <div className="flex max-w-4xl flex-col gap-space-sm"><div className="inline-flex w-fit items-center gap-space-xs rounded-full bg-surface-container-low px-space-sm py-1 font-label-sm text-label-sm font-bold uppercase tracking-wider text-azul"><span className="h-2 w-2 animate-pulse rounded-full bg-azul" />Portafolio Núcleo Capital</div><h1 className="font-display text-headline-lg tracking-tight text-azul lg:text-display">Proyectos gráficos que dejan una <span className="text-tertiary">marca visible.</span></h1><p className="max-w-3xl font-body-lg text-body-lg leading-relaxed text-on-surface-variant">Una selección de proyectos de identidad, fotografía, dirección de arte y diseño editorial desarrollados para marcas que quieren comunicar con intención.</p><div className="flex flex-wrap items-center gap-space-xs pt-space-xs sm:gap-space-sm"><div className="flex items-center gap-1.5 rounded-full bg-surface-container px-space-sm py-1 text-on-surface"><span className="material-symbols-outlined text-base text-azul">photo_camera</span><span className="font-label-md text-label-md">Fotografía comercial</span></div><div className="flex items-center gap-1.5 rounded-full bg-surface-container px-space-sm py-1 text-on-surface"><span className="material-symbols-outlined text-base text-azul">palette</span><span className="font-label-md text-label-md">Identidad y branding</span></div><div className="flex items-center gap-1.5 rounded-full bg-surface-container px-space-sm py-1 text-on-surface"><span className="material-symbols-outlined text-base text-azul">local_shipping</span><span className="font-label-md text-label-md">Producción en Arequipa</span></div></div></div>
      </div>
    </section>
    <section className="bg-surface-container-low py-space-3xl"><div className="mx-auto max-w-[1280px] px-gutter-mobile lg:px-gutter-desktop"><div className="mb-space-xl flex items-end justify-between gap-space-md"><div><span className="font-label-sm text-label-sm font-bold uppercase tracking-widest text-azul">Casos seleccionados</span><h2 className="mt-space-xs font-headline-lg text-headline-lg font-bold text-azul">Trabajo que habla por nosotros.</h2></div><span className="hidden font-label-md text-label-md text-outline sm:block">{projects.length} proyectos destacados</span></div><div className="grid gap-space-lg md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <article key={project.slug} className="group flex flex-col overflow-hidden rounded-xl border border-outline-variant/60 bg-surface-container-lowest shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Link to={`/proyectos/${project.slug}`} className="relative block aspect-[4/3] overflow-hidden bg-azul"><img src={project.image} alt={project.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-azul/80 via-transparent to-transparent" /><span className="absolute left-space-md top-space-md rounded-full bg-crema px-space-sm py-1 font-label-sm text-label-sm font-bold text-azul">{project.category}</span><span className="material-symbols-outlined absolute bottom-space-md right-space-md rounded-full bg-tertiary p-2 text-white">arrow_outward</span></Link><div className="flex flex-1 flex-col p-space-lg"><div className="flex items-center gap-space-xs text-tertiary"><span className="material-symbols-outlined text-[18px]">{project.icon}</span><span className="font-label-sm text-label-sm font-bold uppercase tracking-wider">Caso destacado</span></div><h3 className="mt-space-sm font-headline-sm text-headline-sm font-bold text-azul">{project.title}</h3><p className="mt-space-xs font-body-md text-body-md text-on-surface-variant">{project.summary}</p><Link to={`/proyectos/${project.slug}`} className="mt-space-lg inline-flex items-center gap-1 font-label-md text-label-md font-bold text-azul">Ver proyecto <span className="material-symbols-outlined text-[17px] transition group-hover:translate-x-1">arrow_forward</span></Link></div></article>)}</div></div></section>
    <section className="mx-auto w-full max-w-[1280px] px-gutter-mobile py-space-3xl lg:px-gutter-desktop"><div className="rounded-2xl border border-outline-variant/60 bg-surface-container-lowest p-space-xl text-center shadow-sm lg:p-space-2xl"><span className="font-label-sm text-label-sm font-bold uppercase tracking-widest text-tertiary">¿Tienes un proyecto en mente?</span><h2 className="mx-auto mt-space-sm max-w-2xl font-headline-lg text-headline-lg font-bold text-azul">Hagamos que sea el próximo caso destacado.</h2><a href="https://wa.me/51983033938?text=Hola%20Nucleo%20Capital,%20quiero%20cotizar%20un%20proyecto" target="_blank" rel="noreferrer" className="mt-space-lg inline-flex items-center gap-space-xs rounded-full bg-azul px-space-lg py-space-md font-label-lg text-label-lg font-bold text-white transition hover:bg-azul-dark"><span className="material-symbols-outlined">chat</span> Iniciar conversación</a></div></section>
  </div>
);

export default Projects;
