import { Link, useParams } from 'react-router-dom';
import { projects } from '../data/projects';

const ProjectDetail = () => {
  const { slug } = useParams();
  const project = projects.find((item) => item.slug === slug);

  if (!project) return <div className="px-gutter-mobile py-40 text-center"><h1 className="font-headline-lg text-headline-lg text-azul">Proyecto no encontrado</h1><Link to="/proyectos" className="mt-space-lg inline-flex text-azul">Volver a proyectos</Link></div>;

  return <div className="flex w-full flex-col bg-crema pt-20">
    <section className="mx-auto w-full max-w-[1280px] px-gutter-mobile pb-space-2xl pt-space-2xl lg:px-gutter-desktop"><Link to="/proyectos" className="inline-flex items-center gap-1 font-label-md text-label-md font-bold text-azul"><span className="material-symbols-outlined text-[18px]">arrow_back</span> Todos los proyectos</Link><div className="mt-space-xl grid items-end gap-space-xl lg:grid-cols-[1fr_0.55fr]"><div><span className="rounded-full bg-surface-container-lowest px-space-sm py-1 font-label-sm text-label-sm font-bold uppercase tracking-wider text-azul">{project.category}</span><h1 className="mt-space-lg font-display text-display font-bold leading-tight tracking-tight text-azul">{project.title}</h1><p className="mt-space-lg max-w-2xl font-body-lg text-body-lg text-on-surface-variant">{project.description}</p></div><div className="rounded-xl bg-azul p-space-lg text-white shadow-xl"><span className="material-symbols-outlined text-4xl text-tertiary-fixed">{project.icon}</span><p className="mt-space-md font-title-lg text-title-lg">Un proyecto pensado para generar confianza y resultados.</p></div></div></section>
    <section className="bg-surface-container-low py-space-2xl"><div className="mx-auto max-w-[1280px] px-gutter-mobile lg:px-gutter-desktop"><div className="overflow-hidden rounded-2xl shadow-xl"><img src={project.image} alt={project.title} className="h-[280px] w-full object-cover sm:h-[460px]" /></div><div className="mt-space-xl grid gap-space-md md:grid-cols-3">{project.results.map((result) => <div key={result.label} className="rounded-xl bg-surface-container-lowest p-space-lg text-center shadow-sm"><strong className="block font-display text-display font-bold text-azul">{result.value}</strong><span className="font-label-md text-label-md font-bold uppercase tracking-wider text-outline">{result.label}</span></div>)}</div></div></section>
    <section className="mx-auto w-full max-w-[1280px] px-gutter-mobile py-space-3xl lg:px-gutter-desktop"><div className="grid gap-space-2xl lg:grid-cols-[0.8fr_1.2fr]"><div><span className="font-label-sm text-label-sm font-bold uppercase tracking-widest text-tertiary">Qué hicimos</span><h2 className="mt-space-xs font-headline-lg text-headline-lg font-bold text-azul">Una solución completa, de principio a fin.</h2><ul className="mt-space-lg space-y-space-sm">{project.deliverables.map((item) => <li key={item} className="flex items-start gap-space-xs font-body-lg text-body-lg text-on-surface-variant"><span className="material-symbols-outlined text-tertiary">check_circle</span>{item}</li>)}</ul></div><div className="grid gap-space-lg sm:grid-cols-2">{project.gallery.map((item) => <figure key={item.caption} className="overflow-hidden rounded-xl bg-surface-container-lowest shadow-sm"><img src={item.image} alt={item.caption} className="h-64 w-full object-cover transition duration-500 hover:scale-105" /><figcaption className="p-space-md font-label-md text-label-md text-on-surface-variant">{item.caption}</figcaption></figure>)}</div></div></section>
    <section className="px-gutter-mobile pb-space-3xl lg:px-gutter-desktop"><div className="mx-auto flex max-w-[1280px] flex-col items-start justify-between gap-space-lg rounded-2xl bg-azul p-space-xl text-white shadow-xl sm:flex-row sm:items-center lg:p-space-2xl"><div><h2 className="font-headline-md text-headline-md font-bold">¿Quieres un proyecto así para tu empresa?</h2><p className="mt-space-xs font-body-md text-body-md text-blue-100">Conversemos y encontremos la mejor ruta para tu siguiente objetivo.</p></div><a href="https://wa.me/51983033938?text=Hola%20Nucleo%20Capital,%20quiero%20un%20proyecto%20similar" target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-space-xs rounded-full bg-tertiary px-space-lg py-space-md font-label-lg text-label-lg font-bold text-white transition hover:bg-tertiary-container"><span className="material-symbols-outlined">chat</span> Cotizar ahora</a></div></section>
  </div>;
};

export default ProjectDetail;
